### ISSUE TITLE
RPR/SGE Unlisted, RPR Soul Slice always shows as clipping

### ISSUE THREAD

**Issue by oorzkws** [CaiClone/GCDTracker#2]
I understand it's a work in progress, just figured I'd note it. The Soul Slice issue might be connection specific but it doesn't happen with other GCDs. GIF below
![2021-12-18_9-11-34](https://user-images.githubusercontent.com/65210810/146647907-314aaa1d-f7ca-421f-83dd-071f32e573e3.gif)

**Comment by CaiClone** [comment]
Both of these should be fixed in update v1.0.1.2 along with a bunch of common use cases where the same happened.
In case anyone is interested there are a lot of skills that use GCD even though they are not weaponskills on the 57 recast group, I can't find a reliable pattern on which ones these are, so for now I added the found recast groups for each class.

I'll close this, if you still get the problem feel free to reopen it, and thank you for reporting it!

**Comment by oorzkws** [comment]
Hey, thanks for the fix. I've noticed some weirdness with dances, too. Next time I play I can confirm and make a gif to show the issue.
